### ISSUE TITLE
Missing instructions or an example for handling authentication

### ISSUE THREAD

**Issue by flrnmrz** [devopsfaith/api2html#30]
I'm missing an example in the docs on how to handle authentication with api2html. For example, it would be nice to have an example on how get api2html to pass an `Authorization: Bearer <token>` header to the backing REST API.

**Comment by kpacha** [comment]
hi, @flrnmrz 

that feature is not supported. 

api2html is designed to render static websites by consuming open apis. it uses a cached-enabled http client, so consuming private endpoints could end in a catastrophic security breach

cheers
